name: dbt-server CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # TODO: add code linting
  # lint:
  #   name: lint code
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v2

  # TODO: add automated testing
  # test:
  #   name: test code
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v2

  build-staging-image:
    name: build and publish staging image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dbt-core-version: head
            dbt-core-package: https://github.com/dbt-labs/dbt-core/archive/HEAD.tar.gz#egg=dbt-core&subdirectory=core
            dbt-database-adapter: snowflake
            dbt-database-adapter-package: https://github.com/dbt-labs/dbt-snowflake/archive/HEAD.tar.gz#egg=dbt-snowflake
          - dbt-core-version: head
            dbt-core-package: https://github.com/dbt-labs/dbt-core/archive/HEAD.tar.gz#egg=dbt-core&subdirectory=core
            dbt-database-adapter: postgres
            dbt-database-adapter-package: https://github.com/dbt-labs/dbt-core/archive/HEAD.tar.gz#egg=dbt-postgres&subdirectory=plugins/postgres
          - dbt-core-version: head
            dbt-core-package: https://github.com/dbt-labs/dbt-core/archive/HEAD.tar.gz#egg=dbt-core&subdirectory=core
            dbt-database-adapter: redshift
            dbt-database-adapter-package: https://github.com/dbt-labs/dbt-redshift/archive/HEAD.tar.gz#egg=dbt-redshift
          - dbt-core-version: head
            dbt-core-package: https://github.com/dbt-labs/dbt-core/archive/HEAD.tar.gz#egg=dbt-core&subdirectory=core
            dbt-database-adapter: bigquery
            dbt-database-adapter-package: https://github.com/dbt-labs/dbt-bigquery/archive/HEAD.tar.gz#egg=dbt-bigquery
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/docker-build-and-push
        with:
          image-name: dbt-server-${{ matrix.dbt-database-adapter }}-${{ matrix.dbt-core-version }}
          docker-file-path: Dockerfile
          docker-build-args: |
            DBT_CORE_PACKAGE=${{ matrix.dbt-core-package }}
            DBT_DATABASE_ADAPTER_PACKAGE=${{ matrix.dbt-database-adapter-package }}
          registry-endpoint: ${{ secrets.STAGING_FROM_ACCOUNT }}.dkr.ecr.us-east-1.amazonaws.com
          registry-username: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          registry-password: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          push: ${{ github.event_name == 'push' }}

  build-production-image:
    name: build and publish production image
    needs: [build-staging-image]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dbt-core:
          - version: "1.0.0"
            package: "dbt-core==1.0.0"
          - version: "1.0.1"
            package: "dbt-core==1.0.1"
        dbt-database-adapter:
          - name: snowflake
            package: dbt-snowflake
          - name: bigquery
            package: dbt-bigquery
          - name: postgres
            package: dbt-postgres
          - name: redshift
            package: dbt-redshift
        include:
          - dbt-core:
              version: head
              package: https://github.com/dbt-labs/dbt-core/archive/HEAD.tar.gz#egg=dbt-core&subdirectory=core
            dbt-database-adapter:
              name: snowflake
              package: https://github.com/dbt-labs/dbt-snowflake/archive/HEAD.tar.gz#egg=dbt-snowflake
          - dbt-core:
              version: head
              package: https://github.com/dbt-labs/dbt-core/archive/HEAD.tar.gz#egg=dbt-core&subdirectory=core
            dbt-database-adapter:
              name: postgres
              package: https://github.com/dbt-labs/dbt-core/archive/HEAD.tar.gz#egg=dbt-postgres&subdirectory=plugins/postgres
          - dbt-core:
              version: head
              package: https://github.com/dbt-labs/dbt-core/archive/HEAD.tar.gz#egg=dbt-core&subdirectory=core
            dbt-database-adapter:
              name: redshift
              package: https://github.com/dbt-labs/dbt-redshift/archive/HEAD.tar.gz#egg=dbt-redshift
          - dbt-core:
              version: head
              package: https://github.com/dbt-labs/dbt-core/archive/HEAD.tar.gz#egg=dbt-core&subdirectory=core
            dbt-database-adapter:
              name: bigquery
              package: https://github.com/dbt-labs/dbt-bigquery/archive/HEAD.tar.gz#egg=dbt-bigquery
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/docker-build-and-push
        with:
          image-name: dbt-server-${{ matrix.dbt-database-adapter.name }}-${{ matrix.dbt-core.version }}
          docker-file-path: Dockerfile
          docker-build-args: |
            DBT_CORE_PACKAGE=${{ matrix.dbt-core.package }}
            DBT_DATABASE_ADAPTER_PACKAGE=${{ matrix.dbt-database-adapter.package }}
          registry-endpoint: ${{ secrets.INFRA_ROOT_FROM_ACCOUNT }}.dkr.ecr.us-east-1.amazonaws.com
          registry-username: ${{ secrets.INFRA_ROOT_AWS_ACCESS_KEY_ID }}
          registry-password: ${{ secrets.INFRA_ROOT_AWS_SECRET_ACCESS_KEY }}
          push: ${{ github.event_name == 'push' }}
